#!/bin/bash

echo -n "brew install? if not you need git installed [n/Y]"
read -n 1 use_brew

if [ "$use_brew" == "Y" ]; then
  ruby -e "$(curl -fsSL https://raw.github.com/Homebrew/homebrew/go/install)"
  brew doctor
  brew bundle
fi

echo "Initializing submodules..."
git submodule init && git submodule update

INSTALLDIR=${1:-$HOME}

echo -n "vim configs? [n/Y]"
read -n 1 use_vim_configs

if [ "$use_vim_configs" == "Y" ]; then
	mv $INSTALLDIR/.vim $INSTALLDIR/.vim.old 2> /dev/null
	mv $INSTALLDIR/.vimrc $INSTALLDIR/.vimrc.old 2> /dev/null
  ln -s $PWD/.vim $INSTALLDIR/.vim
  ln -s $PWD/.vimrc $INSTALLDIR/.vimrc
fi

echo -n "bash configs? [n/Y]"
read -n 1 use_bash_configs

if [ "$use_bash_configs" == "Y" ]; then
	mv $INSTALLDIR/.bash $INSTALLDIR/.bash.old 2> /dev/null
	mv $INSTALLDIR/.bash_profile $INSTALLDIR/.bash_profile.old 2> /dev/null
  ln -s $PWD/.bash $INSTALLDIR/.bash
  ln -s $PWD/.bash_profile $INSTALLDIR/.bash_profile
fi

echo "Git config settings"
echo -n "Name: "
read git_name
echo -ne "\nEmail: "
read git_email

cp $PWD/.gitconfig $INSTALLDIR/.gitconfig
sed -i "s/%%GITNAME%%/$git_name/" $INSTALLDIR/.gitconfig
sed -i "s/%%GITEMAIL%%/$git_email/" $INSTALLDIR/.gitconfig

if [ ! -d $HOME/p ]; then
  echo "project directory, symlink from ~/p will be created"
  echo -n "Dir: "
  read projectdir
  ln -s $HOME/p $projectdir
fi ]

