#!/bin/zsh

#get data and remove colors from output
data=$(curl -s rate.sx/\?n=1 > /dev/null |
  sed 's/\x1B\[[0-9;]\+[A-Za-z]//g' | cat)

price=$(echo $data |
  tail -n 6 |
  head -n 1 |
  cut -d " " -f 10
)

msg=$(echo $data |
  head -n 9 |
  tail -n 3
)

msg="$msg

 $price"

dunstify $msg
echo $msg
echo $price > ~/.btc_price
