#!/usr/bin/env sh

# this file is useful for running functions in a non-interactive shell
# (dmenu, xinit, sxhkd). so we need to source our functions here and
# run them, else we end in an infinite loop. functions are not sourced
# in a non-interactive shell so we create symlinks to this script
# in the $PATH and source the profile.

# source .profile with functions and eval
# symlinked binaries in the $PATH are overwritten by the function calls
. "$DOTFILES"/.profile
eval "${0##*/}"
