#!/bin/bash
VOL="$(pamixer --get-volume)%"
DATE=$(date +%d.%m.%Y)
TIME=$(date +%H:%M)
EXTIP=$(cat ~/.external_ip)
BTC=$(cat ~/.btc_price)
IP=$(for i in `ip r`; do echo $i; done | grep -A 1 src | tail -n1) # can get confused if you use vmware
TEMP="$(($(cat /sys/class/thermal/thermal_zone0/temp) / 1000))C"
AVAIL=$(df -h --output=avail | head -n4 | tail -n1)

xsetroot -name "  $EXTIP | $IP | ♪ $VOL |  $TEMP | $BTC | $AVAIL |  $DATE |  $TIME "


#if acpi -a | grep off-line > /dev/null
#then
#  BAT="Bat. $(acpi -b | awk '{ print $4 " " $5 }' | tr -d ',')"
#  xsetroot -name "$IP $BAT $VOL $TEMP $TIME"
#else
#  xsetroot -name "$EXTIP/$IP $VOL $TEMP $TIME"
#fi
