#!/bin/zsh
# TODO: not hardcore city
city="wels"

#get data and remove colors from output
data=$(curl -s wttr.in/$city > /dev/null |
  sed 's/\x1B\[[0-9;]\+[A-Za-z]//g' | cat)

# get temp
temp=$(echo $data |
  head -n 4 |
  tail -n 1 |
  sed 's/   */:/g' |
  cut -d : -f 4
)

# TODO: use icons for (rain|sun|cloudy|snow)

msg="$city: $temp"
notify-send $msg
echo $msg
echo $temp > ~/.weather # statusbar
